export const COUNTRIES = [
  { code: "CD", name: "Congo (RDC)" },
  { code: "CG", name: "Congo (République)" },
  { code: "CI", name: "Côte d'Ivoire" },
  { code: "SN", name: "Sénégal" },
  { code: "CM", name: "Cameroun" },
  { code: "ML", name: "Mali" },
  { code: "BF", name: "Burkina Faso" },
  { code: "GN", name: "Guinée" },
  { code: "TG", name: "Togo" },
  { code: "BJ", name: "Bénin" },
  { code: "NE", name: "Niger" },
  { code: "GA", name: "Gabon" },
  { code: "GQ", name: "Guinée équatoriale" },
  { code: "CF", name: "République centrafricaine" },
  { code: "TD", name: "Tchad" },
  { code: "RW", name: "Rwanda" },
  { code: "BI", name: "Burundi" },
  { code: "UG", name: "Ouganda" },
  { code: "KE", name: "Kenya" },
  { code: "TZ", name: "Tanzanie" },
  { code: "ET", name: "Éthiopie" },
  { code: "NG", name: "Nigeria" },
  { code: "GH", name: "Ghana" },
  { code: "ZA", name: "Afrique du Sud" },
  { code: "MA", name: "Maroc" },
  { code: "DZ", name: "Algérie" },
  { code: "TN", name: "Tunisie" },
  { code: "FR", name: "France" },
  { code: "BE", name: "Belgique" },
  { code: "CH", name: "Suisse" },
  { code: "US", name: "États-Unis" },
  { code: "CA", name: "Canada" },
  { code: "GB", name: "Royaume-Uni" },
  { code: "DE", name: "Allemagne" },
  { code: "IT", name: "Italie" },
  { code: "ES", name: "Espagne" },
  { code: "PT", name: "Portugal" },
  { code: "NL", name: "Pays-Bas" },
  { code: "CN", name: "Chine" },
  { code: "JP", name: "Japon" },
  { code: "IN", name: "Inde" },
  { code: "BR", name: "Brésil" },
  { code: "AU", name: "Australie" },
  { code: "AE", name: "Émirats arabes unis" },
  { code: "SA", name: "Arabie saoudite" },
].sort((a, b) => a.name.localeCompare(b.name, "fr"));
